name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Type check
        run: npm run type-check

      - name: Validate all members.json
        run: find data -name 'members.json' -exec npm run validate -- {} \;

      - name: Check jobs.json and groups.json are up-to-date
        run: |
          echo "Checking if jobs.json and groups.json are up-to-date..."
          npm run update-metadata

          if ! git diff --exit-code data/jobs.json data/*/groups.json; then
            echo "❌ Metadata files (jobs.json, groups.json) are out of date!"
            echo "Please run the following command and commit the changes:"
            echo "  npm run update-metadata"
            exit 1
          fi

          echo "✅ jobs.json and groups.json are up-to-date!"

      - name: Check master.json is up-to-date
        run: |
          echo "Checking if master.json is up-to-date..."
          npm run update-master

          if ! git diff --exit-code data/master.json; then
            echo "❌ master.json is out of date!"
            echo "Please run the following command and commit the changes:"
            echo "  npm run update-master"
            exit 1
          fi

          echo "✅ master.json is up-to-date!"
