name: Validate Data

on:
  pull_request:
    paths:
      - 'data/**/members.json'
  push:
    branches:
      - main
    paths:
      - 'data/**/members.json'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            data/**/members.json

      - name: Validate changed members.json files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Validating the following files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

          # Validate each changed file
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Validating: $file"
            npm run validate -- "$file"

            if [ $? -eq 0 ]; then
              echo "✅ $file is valid"
            else
              echo "❌ $file validation failed"
              exit 1
            fi
          done

      - name: Summary
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "### Validation Results ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All members.json files passed validation!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Validated files:**" >> $GITHUB_STEP_SUMMARY
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "- \`$file\`" >> $GITHUB_STEP_SUMMARY
          done
